# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: cli
    - name: Build
      run: dotnet publish downloader.csproj -c Release -o ./publish
      working-directory: cli

    - name: Copy artifacts to repository root
      run: |
        rm -rf publish
        mkdir -p publish
        cp -R cli/publish/* publish/

    - name: Commit published files
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git add publish

        git diff --staged --quiet && exit 0

        git commit -m "Update published binaries"
        git push
